# Required
version: 2
formats:
  - pdf

# Image to use
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

# Configuration
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  configuration: docs/source/conf.py
